print("Guess Number Between (1 to 9)")
Number=input("Type the number you guess:-")
if(Number<3)
print=("Now add 5")
elif(Number<8)
print( "great work the number is 7 or 6 but give a clue to find the number as a number")
if (Number<7)
print("the number is 6")
if (Number<8)
print("the number is 7")
